version: '3.7'

services:
  bookservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books
    depends_on:
      - bookdb

  bookdb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - bookdb_data:/var/lib/postgresql/data

  authorservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authors
    depends_on:
      - authordb

  authordb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authors
    ports:
      - "5432:5432"
    volumes:
      - authordb_data:/var/lib/postgresql/data

  categoryservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=categories
    depends_on:
      - categorydb

  categorydb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: categories
    ports:
      - "5432:5432"
    volumes:
      - categorydb_data:/var/lib/postgresql/data

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    depends_on:
      - userdb

  userdb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - userdb_data:/var/lib/postgresql/data

volumes:
  bookdb_data:
  authordb_data:
  categorydb_data:
  userdb_data:
